title: apostrophe.how
description: 'How to Use an Apostrophe'
url: 'http://apostrophe.how'
baseurl: ''

# Build settings
encoding: UTF-8
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
kramdown:
  hard_wrap: false
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
gfm_quirks: paragraph_end

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - project.json
  - project.user.json
